#!/bin/sh

WEBHOOK_URL="https://discord.com/api/webhooks/YOUR_WEBHOOK_URL_HERE"
USERNAME=$(git config user.name)
BRANCH=$(git rev-parse --abbrev-ref HEAD)
TIME=$(date '+%d-%m-%Y %H:%M:%S')

MESSAGE="[$TIME] $USERNAME committed to \`$BRANCH\`"

OS="$(uname)"
JSON_PAYLOAD="{\"content\": \"$MESSAGE\"}"

if echo "$OS" | grep -iq "mingw"; then
    curl -H "Content-Type: application/json" -X POST -d "$JSON_PAYLOAD" "$WEBHOOK_URL"
else
    curl -H "Content-Type: application/json" -X POST -d "$JSON_PAYLOAD" "$WEBHOOK_URL"
fi
